### ISSUE TITLE
Investigate Ronny's DX case (Grid)

### ISSUE THREAD

**Issue by czp13** [vaadin/form-filler-addon#46]
Check Ronni's case why Ronni's Grid is not populated properly. (files on slack)

**Comment by mgarciavaadin** [comment]
So several findings with this investigation. 

The involved code is this 
```java 
        TimePicker tp = new TimePicker();
        tp.setId("timeInBerlin add two hours");
        formLayout.add(tp);
.....
.....
  Grid<OrderItem> grid = new Grid<>(OrderItem.class);
        grid.removeAllColumns();
        grid.setId("orders");
        grid.addColumn(OrderItem::getOrderId).setHeader("Order Id").setKey("orderId").setId("orderId");
        grid.addColumn(OrderItem::getItemName).setHeader("Item Name").setKey("itemName").setId("itemName");
//        grid.addColumn(OrderItem::getOrderDate).setHeader("Order Date").setKey("orderDate").setId("orderDate");
//        grid.addColumn(OrderItem::getOrderStatus).setHeader("Order Status").setKey("orderStatus").setId("orderStatus");
//        grid.addColumn(OrderItem::getOrderTotal).setHeader("Order Cost").setKey("orderCost").setId("orderCost");
```

The result of Ronny's DX was showing just one item in the grid while the text describes 5 (same input as TextDemo). It looks like 
- ChatGPTChatCompletionService (a.k.a. newest GPT endpoint/models turbo.16K) is not capable out of the box to understand that the grid with id "orders" wants to collect all the items of the order if only the 2 first columns are included (orderId, itemName). However if all 5 columns are included the result is as expected. 
- ChatGPTService (a.k.a. old GPT endpoint/model davinci) is capable of understanding the grid with id "orders" and collects the items correctly just with the 2 first columns (orderId, itemName). 
- As a side effect of this testing we have discovered that when the id contains spaces JSON mapping is failing with old GPT because out of the box is not formatting the JSON keys with double quotes. This is shown by the error mapping the TimePicker with "tp.setId("timeInBerlin add two hours");"

__SOLUTION__

__OLD GPT__
To fix the old GPT a built in rule in the prompt can be added  "Generate the JSON object with all keys being double quoted." This fix is going to be added to the addon through the ChatGPTService. 

__NEW GPT__
To fix the new GPT just adding a extra field instruction for the grid fixes the problem:
```java
extraFieldInstructions.put(grid, "This field includes the items included in the order");
```
This fix cannot be added as built in as it is a particular case, anyways it remarks the feedback that the new model it is not always better than the old one and __should be highlighted in the documentation__.

**Comment by mgarciavaadin** [comment]
@czp13 I think we can consider the investigation closed. Issue to improve the old GPT prompt is created #58
